version: '3'
services:
  docker-app:
    image: celiobarros/uds
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres
  docker-postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=uds
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres